version: '3'
services:
  node:
    image: node:10.15.0-alpine
    working_dir: /app
#    command: ["/bin/sh", "-c", "npm install -D live-server@1.2.1"]
#    command: ["/bin/sh", "-c", "npm install lodash@4.17.11"]
#    command: ["/bin/sh", "-c", "npx live-server"]
#    command: ["/bin/sh", "-c", "npx webpack-dev-server"]
    command: ["/bin/sh", "-c", "npm run start"]
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
#    command: npm init -y
volumes:
  node_modules:
    driver: 'local'